vim.opt.number = true
vim.opt.relativenumber = true
vim.opt.clipboard = "unnamedplus"
vim.opt.inccommand = "split"
vim.opt.splitbelow = true
vim.opt.splitright = true
vim.opt.tabstop = 8
vim.opt.expandtab = true
vim.opt.virtualedit = 'block'
vim.opt.termguicolors = true
vim.opt.ignorecase = true
vim.opt.scrolloff = 8
vim.o.signcolumn = 'yes'
vim.o.undofile = true
vim.o.undodir = vim.fn.stdpath('state') .. '/undo'
vim.opt.cul = true
